   name: GitHub Pages

   on:
     push:
       branches: [ main ]

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2
       
       - uses: dart-lang/setup-dart@v1
       
       - name: Install dependencies
         run: dart pub get
       
       - name: Build web
         run: dart compile js web/main.dart -o build/web/main.dart.js
       
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./build/web